import io.netty.channel.PendingBytesTracker.DefaultChannelPipelinePendingBytesTracker;
public class FunctionUse5824 {
public void funcUse() {
DefaultChannelPipelinePendingBytesTracker defaultchannelpipelinependingbytestracker = new DefaultChannelPipelinePendingBytesTracker();
defaultchannelpipelinependingbytestracker.incrementPendingOutboundBytes(null);
}
}